language: python
python:
    - "3.4"
# command to install dependencies
sudo: required
install:
    - sudo pip3 install python-qt5
    - "pip3 install -r requirements.txt"
# command to run tests
script: nosetests
