language: python
python:
    - "3.4"
# command to install dependencies
sudo: required
install:
    - sudo apt-get update
    - sudo apt-get -y install python3-pyqt5 python3-pip libfreetype6 libfreetype6-dev
    - "pip3 install -r requirements.txt"
# command to run tests
script: nosetests
