language: python
python:
    - "3.4"
# command to install dependencies
sudo: required
dist: trusty
before_install:
    - sudo apt-get -y install python-qt5
install:
    - "pip install -r requirements.txt"
# command to run tests
script: nosetests
