language: python
python:
    - "3.4"
# command to install dependencies
sudo: required
before_install:
    - sudo apt-get install python-qt5
install:
    - "pip install -r requirements.txt"
# command to run tests
script: nosetests
